apiVersion: v1
kind: Service
metadata:
  name: "kubernetes-demo-api-service"
spec:
  selector:
    app: "kubernetes_demo_api"
  type: NodePort
  ports:
  - protocol: "TCP"
    port: 8000
    nodePort: 32222
    targetPort: 8000
