apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes.demo.app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kubernetes_demo_app
    spec:
      containers:
        - name: kubernetes-demo-app
          image: registry.runnable.com/runnable/api
          ports:
            - containerPort: 8000
          env:
          - name: RETHINKDB_HOST
            value: rethinkdb-db-access
          - name: PORT
            value: "8000"
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github
                key: token
