apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    db: mongodb
  name: mongodb
spec:
  template:
    metadata:
      labels:
        db: mongodb
    spec:
      containers:
      - image: mongodb
        args:
          - "mongod"
        imagePullPolicy: Always
        name: rethinkdb
        ports:
        - containerPort: 8080
          name: admin
        - containerPort: 28015
          name: driver
        - containerPort: 29015
          name: cluster
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
      volumes:
      - name: mongo-storage
        emptyDir: {}
